---
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
title: 
author:
- name: Sangeeta Bhatia
  affiliation: Imperial College London
abstract: 
keywords: 
date: "Y"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
# spacing: double
bibliography: 
biblio-style: apsr
endnote: no
---


```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width = 12, fig.height = 6, echo = FALSE,
                      warning = FALSE, message = FALSE,
                      fig.path = "figures/")

```

```{r setup}
library(ggplot2)
library(ggthemes)
library(scales)
library(lemon)
library(dplyr)
devtools::load_all()

```


```{r ds1_params}

species   <- "Humans"
disease   <- "Ebola"
case.type <- "SCC"

```

# Data clean-up

Visualising the raw data.



```{r}

healthmap <- here::here("data", "CaseCounts/raw/HealthMap_Ebola_GNE_WHO.csv") %>%
             read.csv(stringsAsFactors = FALSE) %>%
             filter(Species == species & Disease == disease)


```

```{r hm_rawviz, eval = TRUE}

healthmap.raw <- healthmap %>%
                  select(Issue.Date, SC, SD, CC, CD, Country) %>%
                  tidyr::gather(case_type,
                                count, -c(Issue.Date, Country)) 
    

healthmap.raw$Issue.Date %<>% as.Date(format = "%m/%d/%y")

p <- healthmap.raw %>%
     ggplot(aes(Issue.Date, count, color = case_type)) +
     geom_point(size = 1.1, stroke = 0, shape = 16) +
     facet_wrap(~Country) +
     xlab("") + ylab("Cumulative Case Count")

p <- p + geom_rangeframe() + theme_tufte() 
p <- p + theme(axis.text.x = element_text(angle = 80, hjust = 1))
p <- p + theme(legend.title = element_blank())
p <- p + xlab("")
p <- p + scale_x_date(date_labels =  "%b %Y")
p

```
The data clean-up consists of the following steps:
1. Extract the cumulative case count as a sum of suspected and
confirmed cases.
2. Merge duplicate alerts.
3. Remove outliers and interpolate missing data.
4. Determine the incidence count from the cumulative case count.


```{r}


cols.to.keep <- c("Location", "Country", "Disease", "Species",
                   "HealthMap.Alert.ID", "Headline", "URL",
                  "Alert.Tag", "Feed.Name", "Lon", "Lat")
## These are columns we generate ourselves later on
cols.to.keep <- c(cols.to.keep, "Date", "Cases") 

## params for outlier removal.
use.last   <- 20
p.within.k <- 0.50
k.sd       <- interval_width_for_p(use.last,
                                   1 - p.within.k) %>%     sqrt %>% `[`(2)


by.location <- healthmap %>%
                split(.$Country) %>%
                lapply(function(case.count){
                    case.count %<>% update_cases_column(case.type) 
                    results <- list(update_cases_col =
                                        case.count[, c("Date", "Cases")])
                    case.count %<>% merge_duplicates(cols.to.keep)
                    results    %<>% c(merge_duplicates =
                                          list(case.count[, c("Date", "Cases")]))
                    
                    case.count %<>% arrange(Date) 

                    not.na          <- which(!is.na(case.count$Cases))
                    cum.incidence   <- case.count[not.na, c('Date', 'Cases')]
                    first.row       <- case.count[1, c('Date', 'Cases')]
                    first.row$Date  <- first.row$Date - 1
                    first.row$Cases <- 0

                    cum.incidence %<>% rbind(first.row, .)


                   cum.incidence %<>%
                       remove.last.outliers(use.last=use.last, k.sd=k.sd)
                   results %<>% c(outliers_removed = list(cum.incidence)) 

                   cum.incidence %<>% make_monotonically_increasing
                   results %<>% c(make_increasing = list(cum.incidence))
                    
                   cum.incidence %<>% interpolate.missing.data
                   results %<>% c(interpolate  = list(cum.incidence))

                   results %<>% bind_rows(.id = "cleanup_step")

                   return(results)}) 

```

```{r lib_eg, eval = TRUE}

lapply(names(by.location), function(n){
                      df <- by.location[[n]]
                      df$cleanup_step %<>% factor
                      df %<>%
                          mutate(cleanup_step =
                                 forcats::fct_recode(cleanup_step, 
                                     "Cases" = "update_cases_col",
                                     "Merge_Duplicates" = "merge_duplicates",
                                     "Outliers Removed" = "outliers_removed",
                                     "Make increasing" = "make_increasing",
                                     "Interpolate" = "interpolate"))

                      df$cleanup_step %<>% forcats::fct_inorder()
 
                      p <- ggplot(df, aes(Date, Cases)) +
                          facet_wrap(~cleanup_step, nrow = 1) +
                          geom_point(size = 1.1,
                                     stroke = 0,
                                     shape = 16,
                                     colour = "gray") 

                      p <- p + geom_rangeframe() + theme_tufte() 
                      p <- p + theme(axis.text.x = element_text(angle = 80,
                                                                hjust = 1))
                      p <- p + theme(legend.title = element_blank())
                      p <- p + xlab("")
                      p <- p + scale_x_date(date_labels =  "%b %Y")
                      outfile <- paste0("figures/", n, "-cleanup.png")
                      print(outfile)
                      ggsave(outfile, p)
    
    })

```

```{r incid_tall, eval = TRUE}

by.location %<>% lapply(function(df){
                         df %<>% filter(cleanup_step == "interpolate")
                         df$incid <- c(0, diff(df$Cases))
                         df %<>% select(-c(cleanup_step, Cases)) 
                         return(df)})


by.location_weekly <- lapply(by.location, daily.to.weekly) %>%
                       bind_rows(.id = "Country") %>%
                       filter(Country %in% c("Guinea", "Sierra Leone", "Liberia"))

by.location_incid <- bind_rows(by.location, .id = "Country")
by.location_incid %<>% filter(Country %in% c("Guinea", "Sierra Leone", "Liberia"))

```

```{r hm_weekly_incid, eval = TRUE}

by.location_weekly$Date %<>% as.Date
p <- ggplot(by.location_weekly , aes(Date, incid)) +
     geom_point(size = 1.5, stroke = 0, shape = 16) +
    facet_wrap(~Country, scales = "free_y", nrow = 6) +
    ylab("Incidence")

p <- p + geom_rangeframe() + theme_tufte() 
p <- p + theme(axis.text.x = element_text(angle = 80, hjust = 1))
p <- p + theme(legend.title = element_blank())
p <- p + xlab("")
p <- p + scale_x_date(date_labels =  "%b %Y")

p

```

```{r incid_wide, eval = TRUE}

by.location_incid %<>% tidyr::spread(key = Country, value = incid, fill = 0)

hm_wide <- here::here("data", "CaseCounts/processed/HealthMap_Ebola_wide.csv")
readr::write_csv(by.location_incid, path = hm_wide)

```
