---
output: 
pdf_document:
citation_package: natbib
keep_tex: false
fig_caption: true
latex_engine: pdflatex
title: Estimate relative risk profile
author:
- name: Sangeeta Bhatia
affiliation: Imperial College London
abstract: 
keywords: 
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
spacing: double
bibliography: 
biblio-style: apsr
endnote: no
params:
  pow_dist : 1
  K : 1
  pow_N_from : 1
  pow_N_to : 1
  from : équateur
  p_stay: 1
---

```{r setup, eval = TRUE}
library(dplyr)
library(magrittr)
library(stringr)
library(ggplot2)
devtools::load_all()
```

## Workflow

1. Compute the flow matrix using the parameters of the gravity model.
2. Compute the relative risk matrix using $p_{stay}$.
3. Extract the top 10 places most at risk from a given location
   (input).

## Read in ADM0 data

```{r adm0, eval = FALSE}
centroids <- here::here("data/Geography/GravityModel/raw",
                             "adm0_centroids_fixed.tsv") %>%
    readr::read_tsv(col_names = FALSE) 

```
## Read in ADM2 data

```{r adm2, eval = TRUE}
drc_neighbors <- c("Democratic Republic of the Congo",
                   "Republic of Congo",
                   "Gabon",
                   "Angola")
centroids_full <- here::here("data/Geography/GravityModel/raw",
                             "adm2-fixed.txt") %>%
    readr::read_tsv(.) %>%
    filter(ADM0 %in% drc_neighbors)

centroids_full$ADM2 <- tolower(centroids_full$ADM2) %>%
    stringr::str_replace_all("\ ", "") %>%
    stringr::str_replace_all("-", "") 

centroids <- select(centroids_full, ADM2,
                    ID2,
                    Weighted_Centroid_Lon,
                    Weighted_Centroid_Lat,
                    Pop)
```

## Flow Matrix 
```{r flowmat, eval = TRUE}

names(centroids) <- c("country", "id", "lon", "lat", "pop")

flow_from_to <- flow_matrix(
  longitude = centroids$lon,
  latitude = centroids$lat,
  population = centroids$pop,
  place_names = centroids$country,
  model = "gravity",
  K = params$K,
  pow_N_from = params$pow_N_from,
  pow_N_to = params$pow_N_to,
  pow_dist = params$pow_dist
)


## Relative Flow
relative_risk <- flow_from_to / rowSums(flow_from_to, na.rm = TRUE)

## matrix characterising the population movement between geographical units
# pmovement <- probability_movement(relative_risk, params$p_stay)

```

Write it out in a clean format.

```{r write, eval = TRUE}
rel_risk_df <- tibble::rownames_to_column(data.frame(relative_risk),
                                            var = "flow_from")
from_source <- filter(rel_risk_df,
                   flow_from == params$from) %>%
    tidyr::gather(flow_to, relative_flow, -flow_from) 
##    top_n(10)
#from_source$relative_flow <- round(from_source$relative_flow, 3)
from_source <- left_join(from_source,
                         centroids_full,
                         by = c("flow_to" = "ADM2")) %>%
    select(flow_from, flow_to, ADM0, ADM1, relative_flow)

here::here("output",
           paste0("flow_from_",
                  params$from,
                  "_",
                  params$pow_dist,
                  ".csv")) %>% readr::write_csv(x = from_source,
                                                path = .)
```


## Top 10 regions at risk

```{r}
knitr::kable(from_source)
```
