---
output: html_document
title: Analysis of WHO Ebola data
author:
- name: Sangeeta Bhatia
  affiliation: Imperial College London
abstract: 
keywords: 
date: "Y"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
# spacing: double
bibliography: 
biblio-style: apsr
endnote: no
params:
  pow_dist : 2
  t.proj : 300
  n.sim : 2
  n.dates.sim : 49
  p.stay: 0.9
  
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=6, echo=FALSE, warning=FALSE, message=FALSE, fig.path = "output/figures/")
```


```{r setup, echo = FALSE}
library(magrittr)
library(ggplot2)
library(dplyr)
library(EpiEstim)
devtools::load_all()

pow_dist    <- params$pow_dist
t.proj      <- params$t.proj
n.sim       <- params$n.sim
n.dates.sim <- params$n.dates.sim
p.stay      <- params$p.stay


```
# Data clean-up

Read in data prepared using the above code chunks.

```{r data_load, eval = TRUE}
infile <- here::here("data", "CaseCounts/processed/WHO_bydistricts.csv")
WHO_bydistricts <- readr::read_csv(infile)

outfile <- here::here("data", "CaseCounts/processed/WHO_bycountry.csv")
WHO_bycountry   <- readr::read_csv(infile)

```


# Gravity model parameters

```{r gm_params}

pow_N_to <- pow_N_from <- 1
K        <- 1

```

# Comparison with the data from Health Map and ProMed

```{r child = 'WHO-data-analysis-HM-comparison.Rmd', eval = FALSE}
```

# Projection using WHO data

## Projection within Sierra Leone

```{r child = 'WHO-data-analysis-Sierra.Rmd', eval = FALSE}
```

## Projection within Liberia

```{r child = 'WHO-data-analysis-Liberia.Rmd', eval = FALSE}
```

## Projection within Guinea

```{r child = 'WHO-data-analysis-Guinea.Rmd', eval = FALSE}
```

## Projection across all districts within Sierra Leone, Liberia and Guinea

```{r child = 'WHO-data-analysis-alldistricts.Rmd', eval = TRUE}
```

## Evaluating goodness of fit
```{r, eval = FALSE}
outfile         <- "output/alldistricts-lh-tproj-100.csv"
log_likelihood  <- read.csv(outfile, na.strings = "-Inf")

## Replace -Inf by a large negative number

#log_likelihood[is.na(log_likelihood)] <- -900


pstay <- unique(log_likelihood$p.stay)   %>% sort
power <- unique(log_likelihood$pow_dist) %>% sort

z  <- select(log_likelihood, -c(pow_dist, p.stay)) %>%
      rowSums %>%
       matrix(nrow = length(power), byrow = TRUE)

p <- plotly::plot_ly(x = ~pstay, y = ~power, z = ~z) %>% plotly::add_surface()


#p <- plot_ly(x = ~pstay, y = ~power, showscale = TRUE) %>%
#  add_surface(z = ~z300) %>%
#  add_surface(z = ~z500, opacity = 0.98) 

```
